---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pooradays-flight
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pooradays-flight
  template:
    metadata:
      labels:
        app: pooradays-flight
    spec:                        # Spec for the container which will run in the Pod
      containers:
      - name: flight-service
        image: daanvinken/pooradays-flight-service:0.0.1
        imagePullPolicy: Always
        ports:
          - containerPort: 8081
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
#        readinessProbe
#          httpGet:
#            path: /readiness
#            port: 8080
#            scheme: HTTP
#          initialDelaySeconds: 5
#          timeoutSeconds: 1
