---
apiVersion: v1
kind: Service
metadata:
  name: flight-app-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  clusterIP: 10.96.0.2

  selector:
    app: flight-service