version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=pooradays_user_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=woepoe
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  user-service:
    container_name: user-service
    image: daanvinken/pooradays-user-service:0.0.1
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - database
volumes:
  postgres_data: