---
apiVersion: v1
kind: Service
metadata:
  name: user-app-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  clusterIP: 10.96.0.3

  selector:
    app: user-service